public class EIV_ContactWrapClass {
    
    public string Contact_id                    {get;set;}
    public string partyContact_Id               {get;set;}
    public string party_ID                      {get;set;}
    public string Prefix                        {get;set;}
    public string First_Name                    {get;set;}
    public string middleName                    {get;set;}
    public string First_Last_Name               {get;set;}
    public string secondLastName               {get;set;}
    public string title                         {get;set;}
    public string Status                        {get;set;}
    public string Country_code                  {get;set;}
    public string Area_code                     {get;set;}
    public string Phone                         {get;set;}
    public string Phone_number_extension        {get;set;}
    public string Mobile                        {get;set;}
    public string Email                         {get;set;}
    public string TypeContact                   {get;set;}
    public string Source_Created_by             {get;set;}
    public string Source_Updated_by             {get;set;}
    public string Source_Application_ID         {get;set;}
    public Datetime Source_Create_Date          {get;set;}
    public Datetime Source_Last_Update_Date     {get;set;}
    public string Oracle_Created_by             {get;set;}
    public string Oracle_Updated_by             {get;set;}
    public Datetime Oracle_Create_Date          {get;set;}
    public Datetime Oracle_Last_Update_Date     {get;set;}
    public string EntitypartyID				    {get;set;}
    
}