public class EIV_AddressWrapClass {
    
    public string Location_ID                {get;set;}
    public string Street                     {get;set;}
    public string Outdoor_Number             {get;set;}
    public string Interior_Number            {get;set;}
    public string County                     {get;set;}
    public string Municipality               {get;set;}
    public string Country                    {get;set;}
    public string City                       {get;set;}
    public string Zip_Code                   {get;set;}
    public string State                      {get;set;}
    public string Status                     {get;set;}
    public string Purpose                    {get;set;}
    public string party_ID                   {get;set;}
    public string Source_Created_by          {get;set;}
    public string Source_Updated_by          {get;set;}
    public string Source_Application_ID      {get;set;}
    public Datetime Source_Create_Date       {get;set;}
    public Datetime Source_Last_Update_Date  {get;set;}
    public string Oracle_Created_by          {get;set;}
    public string Oracle_Updated_by          {get;set;}
    public Datetime Oracle_Create_Date       {get;set;}
    public Datetime Oracle_Last_Update_Date  {get;set;}
    public string PostalCodeId               {get;set;}
    public string EntityPartyId              {get;set;}
    public string s_397                      {get;set;}
    public string s_789                      {get;set;}
    public string xa7                        {get;set;}
    public string s1u                        {get;set;}
    //public string custAccountID              {get;set;}
    public string addressReference           {get;set;}
    public string addressLinesPhonetic       {get;set;}
    public string normalizedAddress          {get;set;}
    //public string identifyingAddressFlag     {get;set;}

    
    
}