public class ES2_wraper_documents {
    public string requestId 			{get; set;}
    public string sourceAccountId 		{get; set;}
    public string sourceAccountName 	{get; set;}
    public string sourceTopParentId		{get; set;}
    public string sourceTopParentName 	{get; set;}
    public string partyId 				{get; set;}
    public string comment 				{get; set;}
    public string contractNumber 		{get; set;}
    public string anex 					{get; set;}
    public string egPartyId 			{get; set;}
    public string egPartyName 			{get; set;}
    public string vsourceOpId 			{get; set;}
    public string vsourceCAId 			{get; set;}
	public string pOutDocId 			{get; set;}
    public string pOutDocType 			{get; set;}
    public string pOutDocName 			{get; set;}
    public string pOutDocStatus 		{get; set;}
    public string pOutDocURL 			{get; set;}
    public string pOutDocStartDate 		{get; set;}
    public string pOutDocEndDate 		{get; set;}
    public string pOutCreatedBy			{get; set;}
    public string pOutNameCreatedBy		{get; set;}
    public string pOutCreationDate 		{get; set;}
    public string oraId					{get;set;}

   
}