public class ES2_wraper_suscritopor {
	public string pOutKYCIndSignName {get;set;}
    public string pOutKYCIndSignFlag {get;set;}
    public string pOutKYCIndSignPowerFlag {get;set;}
    public string pOutKYCIndSignPublicDeedNum {get;set;}
    public Date pOutKYCIndSignPublicDeedDate {get;set;}
    public string pOutKYCIndSignNotaryName {get;set;}
    public string pOutKYCIndSignNotaryNum {get;set;}
    public string pOutKYCIndSignNotaryState {get;set;}
    public string pOutKYCIndSignDateDay {get;set;}
    public string pOutKYCIndSignDateMonth {get;set;}
    public string pOutKYCIndSignDateYear {get;set;}
}