public class ES2_wraper_PPE {
    public string pOutKYCIndPPEFlag {get;set;}
    public string pOutKYCIndPPEJob {get;set;}
    public string pOutKYCIndPPEAFlag {get;set;}
    public string pOutKYCIndPPEAName {get;set;}
    public string pOutKYCIndPPEARelationship {get;set;}
    
    public string kycOrgPPEFlag {get;set;}
    public string kycOrgPPEJob {get;set;}
    public string kycOrgPPEName {get;set;}
    public string kycOrgPPEAName {get;set;}
    public string kycOrgPPEARelationship {get;set;}
    
    public string pOutKYCOrgPPEABoardJob {get;set;}
    public string pOutKYCOrgPPEABoardName {get;set;}
    public string pOutKYCOrgPPEAName2 {get;set;}
    public string pOutKYCOrgPPEARelationship2 {get;set;}
}