public class ES2_wraper_datos_generales {
    public Date BirthDate {get;set;}
    public string GDRFC {get;set;}
    public string GDCURP {get;set;}
    public string GDNacionalities {get;set;}
    public string kycOrgGDNacionality {get;set;}
    public string GDFEASerialNo {get;set;}
    public string GDPhone {get;set;}
    public string GDEmail {get;set;}
    public string GDActivity {get;set;}
    public string GDBirthCountry {get;set;}
    public string GDBirthState {get;set;}
    public string GDSex {get;set;}
    public string GDMarriageStatus {get;set;}
    public string GDMarriageRegime {get;set;}
    public string GDNameOfSpouse {get;set;}
    
}