public class ES2_wraper_certificadorepresentantelegal {
    public string pOutKYCOrgSignName {get;set;}
    public string pOutKYCOrgSignJob {get;set;}
    public string pOutKYCOrgSignPublicDeedNum {get;set;}
    public Date pOutKYCOrgSignPublicDeedDate {get;set;}
    public string pOutKYCOrgSignNotaryName {get;set;}
    public string pOutKYCOrgSignNotaryNum {get;set;}
    public string pOutKYCOrgSignNotaryState {get;set;}
    public string pOutKYCOrgSignDateDay {get;set;}
    public string pOutKYCOrgSignDateMonth {get;set;}
    public string pOutKYCOrgSignDateYear {get;set;}
}