public class ES2_wraper_coments {
    public string pOutComId {get; set;}
    public string pOutComSection {get; set;}
    public string pOutComComment {get; set;}
    public string pOutComCreatedBy {get; set;}
    public string comNameCreatedBy {get;Set;}
    public string pOutComCreationDate {get; set;}
    public string pOutComUpdatedBy {get; set;}
    public string comNameUpdatedBy {get;set;}
    public string pOutComLastUpdateDate {get; set;}
}