@isTest public class ES2_Wraper_CreditApprovalTest {
	@isTest
    
    
    public static void isTest(){
        ES2_Wraper_CreditApproval instanciaCredit = new ES2_Wraper_CreditApproval();
		instanciaCredit.egProposedName = null;
        instanciaCredit.oppPartyBOFlag = null;
        instanciaCredit.oppPartyGuarantorFlag = null;
        instanciaCredit.oppPartyId = null;
        instanciaCredit.oppPartyName = null;
        instanciaCredit.oppPartyObligorFlag = null;
        instanciaCredit.oppPartyRDEFlag = null;
        
    }
}