public class ES2_Wraper_CREDIT_BUREAU {
    public string CBPartySiteID {get; set;}
    public string CBLegalPartyId {get; set;}
    public string CBLegalPartyAlias {get; set;}
    public string CBRejectReason {get; set;}
    public string CBLetterFlag {get; set;}
    public string RFC {get; set;}
    public string cbCustomerType {get; set;}
    public string cbName {get; set;}
    public string cbSecondName {get; set;}
    public string cbLastName {get; set;}
    public string cbSecondLastName {get; set;}
    public string cbAPIRequestor {get; set;}
    public string CompanyName {get; set;}
    public string Address {get; set;}
    public string ECEntity {get; set;}
    public Date LetterSigningDate {get; set;}
    public string LetterSigningPlace {get; set;}
    public string Alias {get; set;}
    public string Street {get; set;}
    public string intnum {get; set;}
    public string municipality {get; set;}
    public string outnum {get; set;}
    public string Suburb {get; set;}
    public string ZipCode {get; set;}
    public string City {get; set;}
    public string State {get; set;}
    public string Country {get; set;}
    public string County {get; set;}
    public string AutorizationLetter {get; set;}
    public string dummyFlag {get; set;}
    public string cbTransactionId{get;set;}
}