public class ES2_Wraper_NDA {   
    public string Oracle_Account_Name  = null;
    public date StartDate  = null;
    public string Top_Parent_Name  = null;
    public date EndDate  = null;
    public string AssignedGroup  = null;
    public string RequestedBy  = null;
    public string AssignedTo  = null;
    public string NDA_Type = null;
    public string Created_By  = null;
    public date Created_Date  = null;
    public string Update_By  = null;
    public date Last_Update_Date  = null; 
}