@isTest 
public class ES2_wraper_economic_group_requestTest {
	@isTest
    private static void ES2_wraper_economic_group_requestTest(){
        ES2_wraper_economic_group_request instancia = new ES2_wraper_economic_group_request();
        instancia.EGProposedName = null;
        instancia.EGPartyId = null;
        instancia.EGPartyName = null;
        instancia.EGSicId = null;
        instancia.EGSicDescriptioA = null;
    }
}