public class ES2_wraper_DomicilioParticular {
    public string pOutKYCIndAdrStreet {get;set;}
    public string pOutKYCIndAdrOutNum {get;set;}
    public string pOutKYCIndAdrIntNum {get;set;}
    public string pOutKYCIndAdrCounty {get;set;}
    public string pOutKYCIndAdrMunicipality {get;set;}
    public string pOutKYCIndAdrCity {get;set;}
    public string pOutKYCIndAdrState {get;set;}
    public string pOutKYCIndAdrCountry {get;set;}
    public string pOutKYCIndIntAdrZipCode {get;set;}
    
    public string kycOrgAdrStreet {get;set;}
    public string kycOrgAdrOutNum {get;Set;}
    public string kycOrgAdrIntNum {get;set;}
    public string kycOrgAdrCounty {get;Set;}
    public string kycOrgAdrMunicipality {get;set;}
    public string kycOrgAdrCity {get;set;}
    public string kycOrgAdrState {get;set;}
    public string kycOrgIntAdrCountry {get;set;}
    public string kycOrgIntAdrZipCode {get;set;}
}