@isTest
public class ES2_Wraper_NDATest {
	@isTest
    private static void ES2_Wraper_NDATest(){
        
        ES2_Wraper_NDA inst = new ES2_Wraper_NDA();
        inst.Oracle_Account_Name = null;
        inst.StartDate = null;
        inst.Top_Parent_Name = null;
        inst.EndDate = null;
        inst.AssignedGroup = null;
        inst.RequestedBy = null;
        inst.AssignedTo = null;
        inst.NDA_Type= null;
        inst.Created_By = null;
        inst.Created_Date = null;
        inst.Update_By = null;
        inst.Last_Update_Date = null; 
    }
}