public class ES4_wraper_RelatedRequest {
    
    
    public string pOutRequestId 			{get;set;}
    public string pOutRequestType 			{get;set;}
    public string pOutndaType               {get;set;}
    public string pOutSourceAccountId		{get;set;}
    public string pOutSourceTopParentId		{get;set;}
    public string pOutSourceTopParentName	{get;set;}
    public string pOutSourceOpId			{get;set;}
    public string pOutSourceCAId			{get;set;}
    public string pOutStartDate				{get;set;}
    public string pOutEndDate				{get;set;}
    public string pOutRequestStatus			{get;set;}
    public string pOutCreatedBy				{get;set;}
    public string pOutRequestedBy			{get;set;}
    public string pOutActiveFlag			{get;set;}
    public string pOutCreationDate			{get;set;}
    public string pOutLastUpdateDate		{get;set;}
    public string pOutFinantialEntity		{get;set;}
    public string nameCreatedBy				{get;set;}
    public string nameRequestedBy 			{get;Set;}
    public string nameUpdatedBy				{get;Set;}
    public string nameAssignedTo			{get;set;}
    
    public string pOutProcessName 			{get;set;}
    public string pOutPartyId				{get;set;}
    public string pOutPartyName				{get;set;}
    public string pOutEGPartyId				{get;set;}
    public string pOutEGPartyName			{get;set;}
    public string pOutRootRequestId 		{get;set;}
    public string pOutAssignedGroup			{get;set;}
    public string pOutAssignedTo			{get;set;}
    public string pOutAssignedDate			{get;set;}
    public string pOutUpdatedBy				{get;set;}
    public string pOutSolvedBy				{get;set;}
    public string pOutSolvedDate			{get;set;}
    public string docTypesToURL				{get;set;}
    
    public void testRelated()
    {
        this.pOutRequestId 			 = '';
        this.pOutRequestType 		 = '';
        this.pOutndaType             = '';
        this.pOutSourceAccountId	 = '';
        this.pOutSourceTopParentId	 = '';
        this.pOutSourceTopParentName = '';
        this.pOutSourceOpId			 = '';
        this.pOutSourceCAId			 = '';
        this.pOutStartDate			 = '';
        this.pOutEndDate			 = '';
        this.pOutRequestStatus		 = '';
        this.pOutCreatedBy			 = '';
        this.pOutRequestedBy		 = '';
        this.pOutActiveFlag			 = '';
        this.pOutCreationDate		 = '';
        this.pOutLastUpdateDate		 = '';
        this.pOutFinantialEntity	 = '';
        this.nameCreatedBy			 = '';
        this.nameRequestedBy 		 = '';
        this.nameUpdatedBy			 = '';
        this.nameAssignedTo			 = '';
        this.pOutProcessName 		 = '';
        this.pOutPartyId			 = '';
        this.pOutPartyName			 = '';
        this.pOutEGPartyId			 = '';
        this.pOutEGPartyName		 = '';
        this.pOutRootRequestId 		 = '';
        this.pOutAssignedGroup		 = '';
        this.pOutAssignedTo			 = '';
        this.pOutAssignedDate		 = '';
        this.pOutUpdatedBy			 = '';
        this.pOutSolvedBy			 = '';
        this.pOutSolvedDate			 = '';
        this.docTypesToURL			 = '';        
        
    }
    
}