public class ES5_wraper_LA_modificacion {
    public string laMModificationId {get; set;}
    public string laMMDocumentId {get; set;}
    public string laMMReformaTotal {get; set;}
    public string laMMEscritura {get; set;}
    public string laMMFecha {get; set;}
    public string laMMFederatarioPublico {get; set;}
    public string laMMRLugar {get; set;}
    public string laMMRFecha {get; set;}
    public string laMMRDatos {get; set;}
    public string laMMObservaciones {get; set;}
    public string laMMActiveFlag {get; set;}
    public string laMMCreatedBy {get; set;}
    public string laMMCreationDate {get; set;}
    public string laMMLastUpdatedBy {get; set;}
    public string laMMLastUpdateDate {get; set;}
    public string laMMNameCreatedBy {get; set;}
    public string laMMNameUpdatedBy {get; set;}
}