public class ES5_wraper_LA_limitante {    
    public string laMLLimatingId {get; set;}
    public string laMLLimitante {get; set;}
    public string laMLDocumentID {get;set;}
    public string laMLEscritura {get; set;}
    public string laMLFecha {get; set;}
    public string laMLFederatarioPublico {get; set;}
    public string laMLRLugar {get; set;}
    public string laMLRFecha {get; set;}
    public string laMLRDatos {get; set;}
    public string laMLActiveFlag {get; set;}
    public string laMLCreatedBy {get; set;}
    public string laMLCreationDate {get; set;}
    public string laMLLastUpdatedBy {get; set;}
    public string laMLLastUpdateDate {get; set;}
    public string laMLNameCreatedBy {get; set;}
    public string laMLNameUpdatedBy {get; set;}
}