public class ES5_wraper_LA_Estatutos {
    
    public string pOutlaEEstatutoID {get; set;}
    public string pOutlaEEstatuto {get; set;}
    public string pOutlaEFecha {get; set;}
    public string pOutlaEComentarios {get; set;}
    public string pOutlaEObservaciones {get; set;}
    public string pOutlaEActiveFlag {get; set;}
    public string pOutlaECreatedBy {get; set;}
    public string pOutlaECreationDate {get; set;}
    public string pOutlaELastUpdatedBy {get; set;}
    public string pOutlaELastUpdateDate {get; set;}
    public string pOutlaENameCreatedBy {get; set;}
    public string pOutlaENameUpdatedB {get; set;}
    
}