@Istest
public class IST_ST_PQ_Income_Fee_Wrapper_Test {

    @Istest
    public static void ResolvedTestIncome(){
        
        IST_ST_PQ_Income_Fee_Wrapper_cls.query_All_Fields a = new IST_ST_PQ_Income_Fee_Wrapper_cls.query_All_Fields();
        a.CreatedById='a2YS00000032VKOMA2';
        a.CurrencyIsoCode='IsoCode';
        a.IST_Amount=1.1;
        a.IST_Calculation_Index=1;
        a.IST_Description='Description';
        a.IST_Paid_Date=Date.today();
        a.IST_Percent=1.1;
        a.IST_Pricing_Quote='a2YS00000032VKOMA2';
        a.IST_stExternalID='a2YS00000032VKOMA2';
        a.LastModifiedById='a2YS00000032VKOMA2';
        a.Name='Eduardo';
        a.recordID='a2YS00000032VKOMA2';
    }

}