@Istest
public class IST_ST_PQ_Rent_Wrapper_Test {
    @Istest
    public static void istStPqRentWrapper(){
        IST_ST_PQ_Rent_Wrapper_cls.query_All_Fields query = new IST_ST_PQ_Rent_Wrapper_cls.query_All_Fields();
        query.recordID = 'a2Y5C000000Dq2BUAS' ;
        query.IST_Advance_Payment=2.5;
        query.IST_Calculation_Index= 2;
        query.CreatedById= 'a2Y5C000000Dq2BUAS';
        query.CurrencyIsoCode='abc';
        query.IST_Description='Pruebas';
        query.LastModifiedById='a2Y5C000000Dq2BUAS';
        query.IST_Num_Payments=2;
        query.IST_Pricing_Quote='a2Y5C000000Dq2BUAS';
        query.Quasi_Lease_Rate=2.5;
        query.Name='Pruebas';
        query.IST_stExternalID='a2Y5C000000Dq2BUAS';
        query.IST_Total_Payments=3.8;
        query.list_ST_PQ_Rent_ASS_Wrapper= new List<ST_PQ_Rent_ASS_Wrapper_cls.query_All_Fields>();
        query.list_ST_PQ_Rent_CFS_Wrapper= new List<ST_PQ_Rent_CFS_Wrapper_cls.query_All_Fields>();
   
        
    }

}