@isTest
public class ST_PQ_Loan_ASS_Wrapper_Test {
    @isTest static void WrapperTest () {
        ST_PQ_Loan_ASS_Wrapper_cls.query_All_Fields Test = new ST_PQ_Loan_ASS_Wrapper_cls.query_All_Fields();
        Test.recordID = 'a40m0000000XcDEAA0';
		Test.Balance = 500000;
		Test.CreatedById = 'a40m0000000XcDEAA0';
		Test.CurrencyIsoCode = '352423';
		Test.Amort_Date = '25/12/2019';
		Test.Funding = 20000;
		Test.Interest = 12000;
		Test.LastModifiedById = 'a40m0000000XcDEAA3';
		Test.Loan = 'a40m0000000XcDEAA5';
		Test.Name = 'Ejemplo';
		Test.Payment = 130000;
		Test.Principal = 23455633;
		Test.Step = 6;
    }
}