@Istest
public class ST_PQ_Rent_ASS_Wrapper_Test {
    @Istest
       public static void ResolvedTestPQRentASS(){
           ST_PQ_Rent_ASS_Wrapper_cls.query_All_Fields a= new ST_PQ_Rent_ASS_Wrapper_cls.query_All_Fields();
           a.recordID='a2YS00000032VKOMA2';
           a.Balance =0.0;
           a.CreatedById='a2YS00000032VKOMA2';
           a.CurrencyIsoCode='IsoCode';
           a.Amort_Date='Amort';
           a.Funding=0.0;
           a.Interest=0.0;
           a.LastModifiedById='a2YS00000032VKOMA2';
           a.Payment=0.0;
           a.Principal=0.0;
           a.Step=1;
           a.rent='a2YS00000032VKOMA2';
           a.Name='Eduardo';
       }

}