@IsTest
public class ST_PQ_Rent_CFS_Wrapper_Test {
    @IsTest
    public static void stPqRentCfsWrapperTest() {
        ST_PQ_Rent_CFS_Wrapper_cls.query_All_Fields query = new ST_PQ_Rent_CFS_Wrapper_cls.query_All_Fields();
        query.recordID='a2Y5C000000Dq2BUAS';
        query.Amount=3.8;
        query.Balance= 6.1;
        query.CreatedById='a2Y5C000000Dq2BUAS';
        query.CurrencyIsoCode='MXN';
        query.Start_Accrual='start';
        query.LastModifiedById='a2Y5C000000Dq2BUAS';
        query.Rent = 'a2Y5C000000Dq2BUAS';
        query.Name='Name';
        query.Num_Pmts= 2;
        query.Period='Period';
        query.Rate=8.3;
        query.Step=1;
        query.Timing='Pruebas';
        query.End_Accrual='End';
        query.TypeRent='TypeRent';
        
        
    }

}