@Istest
public class ST_PQ_Periodic_Expense_CFS_Wrapper_Test {
     @Istest
    public static void stPqPeriodicExpenseCfsWrapper(){
        ST_PQ_Periodic_Expense_CFS_Wrapper_cls.query_All_Fields query = new  ST_PQ_Periodic_Expense_CFS_Wrapper_cls.query_All_Fields();
        query.recordID='a2Y5C000000Dq2BUAS';
        query.Amount = 5.5; 
        query.Balance= 3.5;
        query.CreatedById='a2Y5C000000Dq2BUAS';
        query.CurrencyIsoCode='abc';
        query.Start_Accrual='pruebas';
        query.LastModifiedById='a2Y5C000000Dq2BUAS';
        query.Num_Pmts=3;
        query.Period='period';
        query.Periodic_Expense='a2Y5C000000Dq2BUAS';
        query.Name='Pruebas';
        query.Rate=2.4;
        query.Step=2.7;
        query.Timing='timing';
        query.End_Accrual='End Accrual';
        query.Type='Type';
    }
    
    
}