@Istest
public class ST_PQ_Loan_CFS_Wrapper_Test {
   @Istest
    public static void ResolvedTestPQLoanCFS(){
         
        ST_PQ_Loan_CFS_Wrapper_cls.query_All_Fields c= new ST_PQ_Loan_CFS_Wrapper_cls.query_All_Fields();
        c.Amount=0.0;
        c.Balance=0.0;
        c.CreatedById='a2YS00000032VKOMA2';
        c.CurrencyIsoCode='IsoCode';
        c.End_Accrual='EndActual';
        c.LastModifiedById='a2YS00000032VKOMA2';
        c.Loan='a2YS00000032VKOMA2';
        c.Name='Eduardo';
        c.Num_Pmts=1;
        c.Period='Period';
        c.Rate=0.0;
        c.recordID='a2YS00000032VKOMA2';
        c.Start_Accrual='StartActual';
        c.Step=1;
        c.Timing='Timing';
        c.TypeLoan='TypeLoan';
        
    }
    }