@Istest
public class ST_PQ_Periodic_Income_CFS_Wrapper_Test {
    @Istest
     public static void ResolvedTestPQPeriodicIncomeCFS(){
         
         ST_PQ_Periodic_Income_CFS_Wrapper_cls.query_All_Fields a= new ST_PQ_Periodic_Income_CFS_Wrapper_cls.query_All_Fields();
             a.Amount=0.0;
             a.Balance=0.0;
             a.CreatedById='a2YS00000032VKOMA2';
             a.CurrencyIsoCode='IsoCode';
             a.End_Accrual='EndActual';
             a.LastModifiedById='a2YS00000032VKOMA2';
             a.Name='Eduardo';
             a.Num_Pmts=1;
             a.Period='Period';
             a.Periodic_Income='a2YS00000032VKOMA2';
             a.Rate=0.0;
             a.recordID='a2YS00000032VKOMA2';
             a.Start_Accrual='StartActual';
             a.Step=0.0;
             a.Timing='Timing';
             a.Type='Type';
        
        
        
    }

    
    
}