@isTest
public class ST_PQ_TV_Schedule_Step_Wrapper_Test {
    @isTest static void Wrapper_Test (){
        ST_PQ_TV_Schedule_Step_Wrapper_cls.query_All_Fields Test = new ST_PQ_TV_Schedule_Step_Wrapper_cls.query_All_Fields();
        Test.recordID = 'a40m0000000XcDEAA0';
        Test.Advance_Debt_Service = 2345323;
        Test.Advance_Rent = 120000;
        Test.Arrears_Debt_Service = 35000;
        Test.Arrears_Rent = 34000;
        Test.CreatedById = 'a40m0000000XcDEAA2';
        Test.CurrencyIsoCode = '564343';
        Test.TV_Date = '23/12/2019';
        Test.LastModifiedById = 'a40m0000000XcDEAA3';
        Test.Number_of_Payments_Scheduled = 6;
        Test.Quote = 'a40m0000000XcDEAA4';
        Test.Termination_Value_Amount = 120000;
        Test.Termination_Value_Percent = 35;
        Test.Total_Due_On_Termination = 20000;
        Test.Name = 'Ejemplo';
    }
}