@istest
public class takedownTableDocumentsWrapper_test {
    @istest
    public static void wrapper(){
        takedownTableDocumentsWrapper_cls.TableElement Test = new takedownTableDocumentsWrapper_cls.TableElement();
        Test.id = 'a40m0000000XcDEAA0';
		Test.name = 'Ejemplo';
		Test.TKD_fm_validation = 's';
		Test.TKD_ls_Status  = 's';
		Test.TKD_pd_Takedown_CP  = 'a2Ym0000009H3GsEAK';
		Test.TKD_txt_Content_Version_ID = '068m0000000P0yTAAS';
		Test.TKD_txt_Document_ID = '069m0000000P2ZIAA0';
		Test.TKD_txt_Extension = 'xml';
    	Test.TKD_ls_asset_type = 'Equipo nuevo (Otra maquinaria y equipo)';
    	Test.AccountId = '001m000000wdaVaAAI';
		Test.Base64 = '2';
    }
}