@Istest
public class Takedown_Supplier_Site_Test {
    @isTest static void TakedownSupplierSite(){
        Takedown_Supplier_Site SuppSite = new Takedown_Supplier_Site();
        SuppSite.rfc='ATB100630PH8';
        SuppSite.name='ASFALTOS TECNICOS DE LA BAJA, S.A. DE C.V.';					
        SuppSite.currencyCode='MXN';				
        SuppSite.taxCode='AP_NO_IVA';					
        SuppSite.nameSite='DMXNO-002-6984';					
     	SuppSite.amlHits='false';					
   		SuppSite.oracleSupplier	='438190';		
    	SuppSite.idSupplier	='a1Um0000002Bkc1EAC';			
    	SuppSite.idSite	='a4Gm00000000lw3EAA';				
    	SuppSite.invoice ='Factura CFDIv33_A16588_08112019';
    }
}