public class Takedown_Supplier_Site {
    	@AuraEnabled public string rfc 						{get; set;}
    	@AuraEnabled public string name 					{get; set;}
        @AuraEnabled public String currencyCode				{get; set;}
        @AuraEnabled public String taxCode					{get; set;}
        @AuraEnabled public String nameSite					{get; set;}
     	@AuraEnabled public String amlHits					{get; set;}
   		@AuraEnabled public String oracleSupplier			{get; set;}
    	@AuraEnabled public String idSupplier				{get; set;}
    	@AuraEnabled public String idSite					{get; set;}
    	@AuraEnabled public String invoice 					{get; set;}
}