/**
 * @description       : 
 * @author            : eduardo.amiens@outlook.com
 * @group             : 
 * @last modified on  : 10-09-2020
 * @last modified by  : eduardo.amiens@outlook.com
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   10-09-2020   eduardo.amiens@outlook.com   Initial Version
**/
global with sharing class WS_UploadInvoicesWrapper {
    global String title {get;set;}
    global String base64Dcument {get;set;}
    global String extension {get;set;}
}