global without sharing class WS_ValidateInvoicesWrapper {
    global string Id {get;set;}
    global string name {get;set;}
    global string TKD_pd_Takedown_CP {get;set;}
    global string TKD_txt_Content_Version_ID {get;set;}
    global string TKD_txt_Document_ID {get;set;}
    global string TKD_txt_Extension {get;set;}
    global string TKD_ls_asset_type {get;set;}
    global string AccountId {get;set;}
}