const FILESUP =
[
'Supplier__c.TKD_tx_amlHits__c',
'Supplier__c.TKD_A_os_de_garant_a_del_activo__c',
'Supplier__c.Categoria__c',
'Supplier__c.TKD_tx_Contexto__c',
'Supplier__c.CreatedById',
'Supplier__c.TKD_Cuantos_clientes_de_EC_han_traido__c',
'Supplier__c.CurrencyIsoCode',
'Supplier__c.TKD_C_ha_trabajado_con_el_proveedor__c',
'Supplier__c.TKD_chkb_HaveInvoice__c',
'Supplier__c.TKD_tl_hitsDescription__c',
'Supplier__c.LastModifiedById',
'Supplier__c.TKD_L_deres_en_venta_de_este_activo__c',
'Supplier__c.TKD_Monto_Invoice__c',
'Supplier__c.Nacionalidad__c',
'Supplier__c.TKD_Numero_de_veces_que_hemos_trabajo__c',
'Supplier__c.Opini_n_positiva_del_SAT__c',
'Supplier__c.TKD_un_oracleSupplier__c',
'Supplier__c.TKD_Pagina_web_existente__c',
'Supplier__c.TKD_Presencia_en_otras_ciudades_regiones__c',
'Supplier__c.TKD_Proveedores_sustitutos__c',
'Supplier__c.TKD_Que_montonoshafacturado_el_proveedor__c',
'Supplier__c.TKD_ls_Pais_de_residencia__c',
'Supplier__c.TKD_Revision_de_facturas_origen__c',
'Supplier__c.TKD_Se_encuentra_correcto_en_el_BIL__c',
'Supplier__c.TKD_Se_encuentra_en_Google_Search__c',
'Supplier__c.TKD_quien_es_quien__c',
'Supplier__c.TKD_Servicio_post_venta__c',
'Supplier__c.TKD_pd_Supplier_in_approval__c',
'Supplier__c.TKD_tx_Supplier_Unique_ID__c',
'Supplier__c.TKD_ls_Tipo_de_tercero__c',
'Supplier__c.TKD_Tipo_de_proveedor__c',
'Supplier__c.TKD_Validaci_n_de_RFC_ante_el_SAT__c',
'Supplier__c.TKD_tx_Vat_Registration_Num__c',
'Supplier__c.TKD_Vendor_ID__c',
'Supplier__c.TKD_tx_Vendor_Name__c',
'Supplier__c.Name',
'Supplier__c.TKD_Tipo_de_Scorecard__c',
'Supplier__c.TKD_tx_Vendor_name_alternative__c',
'Supplier__c.TKD_Verificacion_de_domicilio__c'  
];


export {FILESUP}